[Content]
Bootable=yes
Bootloader=grub
RootPassword=root
Locale=C.UTF-8
Timezone=Europe/Paris
Keymap=fr
RemoveFiles=/etc/yum.repos.d/mkosi.repo

Packages=kernel,grub2-efi,grub2-tools,grubby,grub2-common,grub2-efi-x64-modules,shim-x64
Packages=NetworkManager,vim,dnf,iproute,vim-minimal,openssh-server
Packages=afb-app-manager,afb-app-manager-rpm,afb-binder,sec-lsm-manager-smack,sec-smack-rules
KernelCommandLineExtra='console=ttyS0 cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1 rw rootwait security=smack loglevel=7 fsck.mode=skip'

# Creation an archive of the image + bmapfile for flashing
PostOutputScripts=scripts/postoutput/99-redpesk.sh
# Extract installed packages list
FinalizeScripts=scripts/finalize/50-manifest.sh
PostInstallationScripts=scripts/postinstall/50-binding-firstboot.sh

[Build]
WithNetwork=yes
Environment=REDPESK_BSP=redpesk-bsp

[Distribution]
Architecture=x86-64
Distribution=rocky # for compatibility
Release=10

[Output]
Format=disk
OutputDirectory=output

[Validation]
Checksum=yes
